Repository cheeaun/phanpy, pull requests merged in 2024-08, with the labels that each got.

#607 Fix overflow for the columns wrapper
  src/app.css
Labels: bug

#610 fix(shortcuts-settings): `settingsJSON` must be defined if note doesn't exist
  src/components/shortcuts-settings.jsx
Labels: bug

#613 Filter out languages that aren't RFC5646-shaped
  src/utils/localeCode2Text.jsx
Labels: bug, need-research

#615 add phanpy.social.tchncs.de deployment to readme
  README.md
Labels: documentation

#628 New Crowdin updates
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab-KAB.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#630 New Crowdin updates
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fr-FR.po
  src/locales/ko-KR.po
  src/locales/ru-RU.po
  src/locales/zh-CN.po
Labels: i18n

#631 New Crowdin updates
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/eu-ES.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/it-IT.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
Labels: i18n

#632 New Crowdin updates
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fr-FR.po
Labels: i18n

#633 New Crowdin updates
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fr-FR.po
Labels: i18n

#634 New Crowdin updates
  src/locales/eo-UY.po
  src/locales/fa-IR.po
  src/locales/fr-FR.po
Labels: i18n

#635 New Crowdin updates
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
Labels: i18n

#636 New Crowdin updates
  src/locales/fi-FI.po
  src/locales/th-TH.po
Labels: i18n

#638 New Crowdin updates
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/it-IT.po
  src/locales/ru-RU.po
Labels: i18n

#639 New Crowdin updates
  src/locales/ca-ES.po
  src/locales/fi-FI.po
Labels: i18n

#640 New Crowdin updates
  src/locales/ca-ES.po
Labels: i18n

#641 New Crowdin updates
  src/locales/ca-ES.po
Labels: i18n

#643 New Crowdin updates
  src/locales/cs-CZ.po
  src/locales/es-ES.po
  src/locales/fa-IR.po
  src/locales/kab-KAB.po
Labels: i18n

#644 New Crowdin updates
  src/locales/ca-ES.po
  src/locales/es-ES.po
  src/locales/fa-IR.po
  src/locales/kab-KAB.po
Labels: i18n

#646 New Crowdin updates
  src/locales/cs-CZ.po
  src/locales/es-ES.po
  src/locales/fr-FR.po
  src/locales/kab-KAB.po
Labels: i18n

#647 New Crowdin updates
  src/locales/ca-ES.po
  src/locales/fi-FI.po
Labels: i18n

#648 New Crowdin updates
  src/locales/fi-FI.po
Labels: i18n

#649 New Crowdin updates
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab-KAB.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#651 New Crowdin updates
  src/locales/kab-KAB.po
Labels: i18n

#652 New Crowdin updates
  src/locales/kab.po
Labels: i18n

#653 New Crowdin updates
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fi-FI.po
  src/locales/kab.po
  src/locales/lt-LT.po
  src/locales/zh-CN.po
Labels: i18n

#654 New Crowdin updates
  src/locales/ca-ES.po
  src/locales/fa-IR.po
  src/locales/kab.po
  src/locales/lt-LT.po
Labels: i18n

#655 New Crowdin updates
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/kab.po
  src/locales/lt-LT.po
Labels: i18n

#659 New Crowdin updates
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/kab.po
Labels: i18n

#660 New Crowdin updates
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pl-PL.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#663 New Crowdin updates
  src/locales/lt-LT.po
  src/locales/ru-RU.po
Labels: i18n

#664 New Crowdin updates
  src/locales/ar-SA.po
  src/locales/kab.po
  src/locales/ru-RU.po
Labels: i18n

#665 New Crowdin updates
  src/locales/kab.po
  src/locales/ru-RU.po
Labels: i18n

#666 New Crowdin updates
  src/locales/ca-ES.po
  src/locales/es-ES.po
  src/locales/ru-RU.po
Labels: i18n

#668 New Crowdin updates
  src/locales/it-IT.po
Labels: i18n

#669 New Crowdin updates
  src/locales/ca-ES.po
  src/locales/eu-ES.po
  src/locales/fi-FI.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
Labels: i18n

#670 New Crowdin updates
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/ru-RU.po
Labels: i18n

#671 New Crowdin updates
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pl-PL.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#672 New Crowdin updates
  src/locales/ca-ES.po
  src/locales/eu-ES.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/pl-PL.po
  src/locales/ru-RU.po
Labels: i18n

#673 New Crowdin updates
  src/locales/cs-CZ.po
  src/locales/ko-KR.po
Labels: i18n

#675 New Crowdin updates
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pl-PL.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#676 New Crowdin updates
  src/locales/fi-FI.po
  src/locales/kab.po
  src/locales/pt-PT.po
Labels: i18n

#677 New Crowdin updates
  src/locales/fr-FR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
Labels: i18n

#678 New Crowdin updates
  src/locales/ca-ES.po
  src/locales/pt-PT.po
Labels: i18n

#679 New Crowdin updates
  src/locales/pt-PT.po
Labels: i18n

#680 New Crowdin updates
  src/locales/cs-CZ.po
  src/locales/fa-IR.po
  src/locales/kab.po
Labels: i18n

#681 New Crowdin updates
  src/locales/eu-ES.po
  src/locales/pt-PT.po
Labels: i18n

#682 New Crowdin updates
  src/locales/eu-ES.po
  src/locales/pt-PT.po
Labels: i18n

#684 New Crowdin updates
  src/locales/pt-PT.po
Labels: i18n

#685 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/fr-FR.po
Labels: i18n

#686 New Crowdin updates
  src/locales/pt-PT.po
Labels: i18n

#687 New Crowdin updates
  src/locales/pt-PT.po
Labels: i18n

#688 New Crowdin updates
  src/data/catalogs.json
  src/locales/ca-ES.po
  src/locales/ko-KR.po
  src/locales/pl-PL.po
Labels: i18n

#689 New Crowdin updates
  src/locales/es-ES.po
  src/locales/it-IT.po
  src/locales/kab.po
Labels: i18n

#690 New Crowdin updates
  src/data/catalogs.json
  src/locales/pt-PT.po
Labels: i18n

#691 New Crowdin updates
  src/data/catalogs.json
  src/locales/gl-ES.po
Labels: i18n

#692 New Crowdin updates
  src/data/catalogs.json
  src/locales/pt-PT.po
Labels: i18n

#693 New Crowdin updates
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pl-PL.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#694 New Crowdin updates
  src/data/catalogs.json
  src/locales/ca-ES.po
  src/locales/eu-ES.po
  src/locales/fi-FI.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
Labels: i18n

#695 New Crowdin updates
  src/data/catalogs.json
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/kab.po
  src/locales/pl-PL.po
  src/locales/zh-CN.po
Labels: i18n

#697 New Crowdin updates
  src/data/catalogs.json
  src/locales/gl-ES.po
  src/locales/ko-KR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
Labels: i18n

#698 New Crowdin updates
  src/data/catalogs.json
  src/locales/it-IT.po
Labels: i18n

#699 New Crowdin updates
  src/data/catalogs.json
  src/locales/pt-BR.po
Labels: i18n

#700 New Crowdin updates
  src/data/catalogs.json
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n

#701 New Crowdin updates
  src/locales/ko-KR.po
Labels: i18n

#702 New Crowdin updates
  src/data/catalogs.json
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n

#703 New Crowdin updates
  src/data/catalogs.json
  src/locales/pt-BR.po
Labels: i18n

#704 New Crowdin updates
  src/data/catalogs.json
  src/locales/pt-BR.po
  src/locales/ru-RU.po
Labels: i18n

#705 New Crowdin updates
  src/data/catalogs.json
  src/locales/pt-BR.po
Labels: i18n

#706 New Crowdin updates
  src/data/catalogs.json
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n

#707 New Crowdin updates
  src/data/catalogs.json
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n

#708 New Crowdin updates
  src/locales/gl-ES.po
Labels: i18n

#709 New Crowdin updates
  src/locales/es-ES.po
Labels: i18n

#710 New Crowdin updates
  src/data/catalogs.json
  src/locales/fr-FR.po
Labels: i18n

#711 New Crowdin updates
  src/locales/lt-LT.po
Labels: i18n

#713 New Crowdin updates
  src/data/catalogs.json
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pl-PL.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#714 New Crowdin updates
  src/data/catalogs.json
  src/locales/eu-ES.po
  src/locales/lt-LT.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n

#715 New Crowdin updates
  src/data/catalogs.json
  src/locales/ca-ES.po
  src/locales/es-ES.po
  src/locales/gl-ES.po
  src/locales/ru-RU.po
Labels: i18n

#716 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/he-IL.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n
