Repository cheeaun/phanpy, pull requests merged in 2024-11, with the labels that each got.

#906 New Crowdin updates
  src/data/catalogs.json
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nb-NO.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pl-PL.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/uk-UA.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#907 New Crowdin updates
  src/data/catalogs.json
  src/locales/es-ES.po
  src/locales/fr-FR.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/uk-UA.po
Labels: i18n

#909 New Crowdin updates
  src/locales/zh-CN.po
Labels: i18n

#910 New Crowdin updates
  src/locales/fi-FI.po
Labels: i18n

#911 New Crowdin updates
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/pt-PT.po
Labels: i18n

#912 New Crowdin updates
  src/data/catalogs.json
  src/locales/uk-UA.po
Labels: i18n

#913 New Crowdin updates
  src/data/catalogs.json
  src/locales/uk-UA.po
Labels: i18n

#914 New Crowdin updates
  src/data/catalogs.json
  src/locales/uk-UA.po
Labels: i18n

#915 New Crowdin updates
  src/data/catalogs.json
  src/locales/eu-ES.po
  src/locales/uk-UA.po
Labels: i18n

#916 New Crowdin updates
  src/data/catalogs.json
  src/locales/uk-UA.po
Labels: i18n

#917 New Crowdin updates
  src/data/catalogs.json
  src/locales/uk-UA.po
Labels: i18n

#918 New Crowdin updates
  src/data/catalogs.json
  src/locales/uk-UA.po
Labels: i18n

#919 New Crowdin updates
  src/data/catalogs.json
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nb-NO.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pl-PL.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/uk-UA.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#920 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fi-FI.po
  src/locales/lt-LT.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/zh-CN.po
Labels: i18n

#921 New Crowdin updates
  src/locales/ca-ES.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n

#923 New Crowdin updates
  src/locales/ko-KR.po
Labels: i18n

#925 New Crowdin updates
  src/locales/th-TH.po
Labels: i18n

#817 Support exclusive lists with GoToSocial 0.17
  src/components/list-add-edit.jsx
  src/data/features.json
  src/locales/en.po
  src/utils/api.js
  src/utils/store-utils.js
  src/utils/supports.js
Labels: enhancement, gotosocial

#926 New Crowdin updates
  src/data/catalogs.json
  src/locales/th-TH.po
  src/locales/uk-UA.po
Labels: i18n

#928 New Crowdin updates
  src/locales/lt-LT.po
  src/locales/uk-UA.po
Labels: i18n

#931 New Crowdin updates
  src/locales/ca-ES.po
Labels: i18n

#934 New Crowdin updates
  src/data/catalogs.json
  src/locales/th-TH.po
Labels: i18n

#936 New Crowdin updates
  src/locales/es-ES.po
Labels: i18n

#938 fix(lang): respect fallback languages
  src/utils/lang.js
Labels: bug, i18n

#939 New Crowdin updates
  src/locales/ca-ES.po
Labels: i18n

#940 New Crowdin updates
  src/locales/lt-LT.po
Labels: i18n

#942 New Crowdin updates
  src/locales/es-ES.po
Labels: i18n

#945 New Crowdin updates
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n

#947 New Crowdin updates
  src/data/catalogs.json
  src/locales/th-TH.po
Labels: i18n

#948 New Crowdin updates
  src/data/catalogs.json
  src/locales/nb-NO.po
Labels: i18n

#950 New Crowdin updates
  src/data/catalogs.json
  src/locales/it-IT.po
Labels: i18n

#951 New Crowdin updates
  src/locales/es-ES.po
Labels: i18n

#952 New Crowdin updates
  src/locales/fr-FR.po
Labels: i18n

#955 New Crowdin updates
  src/data/catalogs.json
  src/locales/gl-ES.po
Labels: i18n

#957 New Crowdin updates
  src/data/catalogs.json
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nb-NO.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pl-PL.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/uk-UA.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#958 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/fi-FI.po
  src/locales/gl-ES.po
  src/locales/lt-LT.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/zh-CN.po
Labels: i18n
