Repository cheeaun/phanpy, pull requests merged in 2024-12, with the labels that each got.

#961 New Crowdin updates
  src/data/catalogs.json
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nb-NO.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pl-PL.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/uk-UA.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#964 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fi-FI.po
  src/locales/lt-LT.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n

#967 New Crowdin updates
  src/data/catalogs.json
  src/locales/gl-ES.po
  src/locales/ru-RU.po
Labels: i18n

#969 New Crowdin updates
  src/locales/eo-UY.po
Labels: i18n

#972 New Crowdin updates
  src/locales/es-ES.po
Labels: i18n

#970 Added phanpy.linuxusers.in to community deployments
  README.md
Labels: documentation

#984 New Crowdin updates
  src/locales/it-IT.po
Labels: i18n

#985 New Crowdin updates
  src/locales/gl-ES.po
Labels: i18n

#986 New Crowdin updates
  src/data/catalogs.json
  src/locales/fr-FR.po
Labels: i18n

#987 New Crowdin updates
  src/data/catalogs.json
  src/locales/fr-FR.po
  src/locales/zh-CN.po
Labels: i18n

#991 New Crowdin updates
  src/data/catalogs.json
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nb-NO.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pl-PL.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/uk-UA.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#992 New Crowdin updates
  src/data/catalogs.json
  src/locales/lt-LT.po
  src/locales/zh-CN.po
Labels: i18n

#993 New Crowdin updates
  src/data/catalogs.json
  src/locales/fi-FI.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
Labels: i18n

#994 New Crowdin updates
  src/data/catalogs.json
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nb-NO.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pl-PL.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/uk-UA.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#995 New Crowdin updates
  src/data/catalogs.json
  src/locales/eu-ES.po
  src/locales/fi-FI.po
  src/locales/it-IT.po
  src/locales/zh-CN.po
Labels: i18n

#996 New Crowdin updates
  src/data/catalogs.json
  src/locales/ru-RU.po
Labels: i18n

#997 New Crowdin updates
  src/data/catalogs.json
  src/locales/es-ES.po
  src/locales/lt-LT.po
Labels: i18n

#998 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/es-ES.po
Labels: i18n

#999 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n

#1000 New Crowdin updates
  src/data/catalogs.json
  src/locales/gl-ES.po
Labels: i18n

#1005 New Crowdin updates
  src/data/catalogs.json
  src/locales/tr-TR.po
Labels: i18n

#1003 Fix text expander not working correctly in lists
  src/components/compose.jsx
  src/locales/en.po
Labels: bug

#1006 New Crowdin updates
  src/data/catalogs.json
  src/locales/ca-ES.po
Labels: i18n
