Repository cheeaun/phanpy, pull requests merged in 2024-09, with the labels that each got.

#718 New Crowdin updates
  src/data/catalogs.json
  src/locales/ca-ES.po
  src/locales/fi-FI.po
  src/locales/ko-KR.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/zh-CN.po
Labels: i18n

#722 New Crowdin updates
  src/data/catalogs.json
  src/locales/ko-KR.po
  src/locales/uk-UA.po
  src/locales/zh-TW.po
Labels: i18n

#723 New Crowdin updates
  src/data/catalogs.json
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/uk-UA.po
Labels: i18n

#724 New Crowdin updates
  src/data/catalogs.json
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/uk-UA.po
Labels: i18n

#725 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/uk-UA.po
Labels: i18n

#726 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/fa-IR.po
  src/locales/pt-BR.po
Labels: i18n

#727 New Crowdin updates
  src/data/catalogs.json
  src/locales/es-ES.po
  src/locales/fa-IR.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n

#728 New Crowdin updates
  src/locales/fa-IR.po
  src/locales/kab.po
  src/locales/pt-BR.po
Labels: i18n

#729 New Crowdin updates
  src/data/catalogs.json
  src/locales/pt-BR.po
Labels: i18n

#730 New Crowdin updates
  src/locales/fa-IR.po
  src/locales/pt-BR.po
Labels: i18n

#731 New Crowdin updates
  src/locales/pt-BR.po
Labels: i18n

#732 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
Labels: i18n

#733 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fr-FR.po
  src/locales/it-IT.po
  src/locales/ko-KR.po
  src/locales/nl-NL.po
  src/locales/pl-PL.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/zh-TW.po
Labels: i18n

#739 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/es-ES.po
Labels: i18n

#740 New Crowdin updates
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pl-PL.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/uk-UA.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#742 New Crowdin updates
  src/data/catalogs.json
  src/locales/eu-ES.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/kab.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/zh-CN.po
Labels: i18n

#744 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/es-ES.po
Labels: i18n

#746 Configure linguist overrides for this repository
  .gitattributes
Labels: enhancement

#657 Add support for local instance posts
  src/components/compose.jsx
  src/components/status.jsx
  src/locales/en.po
  src/utils/supports.js
  src/utils/visibility-icons-map.js
Labels: enhancement, pleroma, akkoma

#747 New Crowdin updates
  src/locales/ca-ES.po
  src/locales/es-ES.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
Labels: i18n

#748 New Crowdin updates
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n

#749 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n

#750 New Crowdin updates
  src/data/catalogs.json
  src/locales/es-ES.po
  src/locales/fr-FR.po
  src/locales/nl-NL.po
Labels: i18n

#753 New Crowdin updates
  src/data/catalogs.json
  src/locales/fa-IR.po
  src/locales/nl-NL.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n

#754 New Crowdin updates
  src/data/catalogs.json
  src/locales/nl-NL.po
Labels: i18n

#755 New Crowdin updates
  src/locales/gl-ES.po
Labels: i18n

#756 New Crowdin updates
  src/data/catalogs.json
  src/locales/nl-NL.po
  src/locales/pt-BR.po
Labels: i18n

#758 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/fa-IR.po
Labels: i18n

#759 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/zh-CN.po
Labels: i18n

#761 New Crowdin updates
  src/locales/it-IT.po
Labels: i18n

#762 New Crowdin updates
  src/data/catalogs.json
  src/locales/it-IT.po
Labels: i18n

#763 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/fa-IR.po
  src/locales/it-IT.po
  src/locales/nl-NL.po
Labels: i18n

#764 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
Labels: i18n

#765 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
Labels: i18n

#769 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
Labels: i18n

#770 New Crowdin updates
  src/locales/eo-UY.po
  src/locales/es-ES.po
Labels: i18n

#771 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
Labels: i18n

#772 New Crowdin updates
  src/data/catalogs.json
  src/locales/pl-PL.po
  src/locales/pt-BR.po
Labels: i18n

#773 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/pt-PT.po
Labels: i18n

#774 New Crowdin updates
  src/locales/pt-PT.po
Labels: i18n

#775 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/pt-PT.po
Labels: i18n

#776 New Crowdin updates
  src/locales/es-ES.po
Labels: i18n

#780 New Crowdin updates
  src/data/catalogs.json
  src/locales/cs-CZ.po
Labels: i18n

#781 New Crowdin updates
  src/locales/zh-CN.po
Labels: i18n

#782 New Crowdin updates
  src/locales/lt-LT.po
Labels: i18n

#783 New Crowdin updates
  src/data/catalogs.json
  src/locales/fa-IR.po
  src/locales/lt-LT.po
  src/locales/zh-CN.po
Labels: i18n

#785 New Crowdin updates
  src/data/catalogs.json
  src/locales/fa-IR.po
  src/locales/lt-LT.po
  src/locales/zh-CN.po
Labels: i18n

#786 New Crowdin updates
  src/data/catalogs.json
  src/locales/lt-LT.po
Labels: i18n

#787 New Crowdin updates
  src/data/catalogs.json
  src/locales/lt-LT.po
  src/locales/pt-PT.po
Labels: i18n

#789 New Crowdin updates
  src/data/catalogs.json
  src/locales/it-IT.po
  src/locales/lt-LT.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n

#790 New Crowdin updates
  src/data/catalogs.json
  src/locales/lt-LT.po
Labels: i18n

#791 New Crowdin updates
  src/data/catalogs.json
  src/locales/lt-LT.po
Labels: i18n

#792 New Crowdin updates
  src/data/catalogs.json
  src/locales/lt-LT.po
Labels: i18n

#793 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/lt-LT.po
Labels: i18n

#794 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/lt-LT.po
Labels: i18n

#788 Fix editing image descriptions
  src/components/compose.jsx
  src/locales/en.po
Labels: bug

#796 New Crowdin updates
  src/locales/eo-UY.po
Labels: i18n

#797 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/es-ES.po
Labels: i18n

#798 New Crowdin updates
  src/data/catalogs.json
  src/locales/lt-LT.po
Labels: i18n

#799 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/lt-LT.po
Labels: i18n

#800 New Crowdin updates
  src/locales/es-ES.po
  src/locales/lt-LT.po
Labels: i18n

#801 New Crowdin updates
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pl-PL.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/uk-UA.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#802 New Crowdin updates
  src/data/catalogs.json
  src/locales/es-ES.po
  src/locales/fr-FR.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n

#804 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/gl-ES.po
  src/locales/lt-LT.po
Labels: i18n

#805 New Crowdin updates
  src/data/catalogs.json
  src/locales/lt-LT.po
  src/locales/ru-RU.po
Labels: i18n

#806 New Crowdin updates
  src/data/catalogs.json
  src/locales/es-ES.po
  src/locales/fi-FI.po
  src/locales/lt-LT.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n

#807 New Crowdin updates
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/zh-CN.po
Labels: i18n

#809 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/pl-PL.po
Labels: i18n

#810 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/it-IT.po
Labels: i18n

#812 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/lt-LT.po
Labels: i18n

#813 New Crowdin updates
  src/locales/es-ES.po
  src/locales/lt-LT.po
Labels: i18n

#814 New Crowdin updates
  src/locales/eo-UY.po
  src/locales/pt-PT.po
  src/locales/zh-CN.po
Labels: i18n

#815 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/nb-NO.po
Labels: i18n

#816 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/ja-JP.po
Labels: i18n

#818 New Crowdin updates
  src/data/catalogs.json
  src/locales/ja-JP.po
Labels: i18n

#819 New Crowdin updates
  src/data/catalogs.json
  src/locales/gl-ES.po
  src/locales/nb-NO.po
Labels: i18n

#820 New Crowdin updates
  src/locales/es-ES.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
Labels: i18n

#821 New Crowdin updates
  src/data/catalogs.json
  src/locales/kab.po
Labels: i18n

#823 New Crowdin updates
  src/locales/eo-UY.po
  src/locales/es-ES.po
Labels: i18n

#826 New Crowdin updates
  src/locales/eo-UY.po
Labels: i18n

#827 New Crowdin updates
  src/locales/eo-UY.po
  src/locales/es-ES.po
Labels: i18n

#828 New Crowdin updates
  src/locales/ca-ES.po
  src/locales/es-ES.po
Labels: i18n

#829 New Crowdin updates
  src/data/catalogs.json
  src/locales/es-ES.po
  src/locales/nb-NO.po
Labels: i18n

#830 New Crowdin updates
  src/data/catalogs.json
  src/locales/fa-IR.po
Labels: i18n

#831 New Crowdin updates
  src/data/catalogs.json
  src/locales/nb-NO.po
Labels: i18n

#832 New Crowdin updates
  src/locales/lt-LT.po
Labels: i18n

#833 New Crowdin updates
  src/locales/eu-ES.po
Labels: i18n

#834 New Crowdin updates
  src/data/catalogs.json
  src/locales/nb-NO.po
Labels: i18n

#835 New Crowdin updates
  src/data/catalogs.json
  src/locales/nb-NO.po
Labels: i18n

#836 New Crowdin updates
  src/data/catalogs.json
  src/locales/lt-LT.po
Labels: i18n

#837 New Crowdin updates
  src/data/catalogs.json
  src/locales/lt-LT.po
Labels: i18n

#838 New Crowdin updates
  src/data/catalogs.json
  src/locales/eo-UY.po
  src/locales/lt-LT.po
Labels: i18n

#840 New Crowdin updates
  src/data/catalogs.json
  src/locales/lt-LT.po
  src/locales/nb-NO.po
Labels: i18n

#844 New Crowdin updates
  src/locales/es-ES.po
Labels: i18n
