Repository cheeaun/phanpy, pull requests merged in 2024-10, with the labels that each got.

#848 New Crowdin updates
  src/data/catalogs.json
  src/locales/lt-LT.po
Labels: i18n

#851 New Crowdin updates
  src/locales/es-ES.po
  src/locales/pl-PL.po
Labels: i18n

#854 New Crowdin updates
  src/locales/it-IT.po
  src/locales/pl-PL.po
Labels: i18n

#859 New Crowdin updates
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
Labels: i18n

#862 New Crowdin updates
  src/locales/fa-IR.po
  src/locales/it-IT.po
Labels: i18n

#868 New Crowdin updates
  src/locales/ca-ES.po
Labels: i18n

#869 New Crowdin updates
  src/locales/es-ES.po
  src/locales/fa-IR.po
Labels: i18n

#875 New Crowdin updates
  src/data/catalogs.json
  src/locales/nb-NO.po
Labels: i18n

#876 New Crowdin updates
  src/data/catalogs.json
  src/locales/nb-NO.po
Labels: i18n

#735 Allow pasting attachments on Akkoma / Pleroma instances
  src/components/compose.jsx
  src/locales/en.po
  src/utils/store-utils.js
Labels: enhancement, pleroma, akkoma

#877 New Crowdin updates
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nb-NO.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pl-PL.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/uk-UA.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#879 New Crowdin updates
  src/data/catalogs.json
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nb-NO.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pl-PL.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/uk-UA.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#880 New Crowdin updates
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nb-NO.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pl-PL.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/uk-UA.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#881 New Crowdin updates
  src/data/catalogs.json
  src/locales/ca-ES.po
  src/locales/es-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/ru-RU.po
  src/locales/zh-CN.po
Labels: i18n

#887 New Crowdin updates
  src/data/catalogs.json
  src/locales/eu-ES.po
  src/locales/fi-FI.po
  src/locales/nb-NO.po
  src/locales/ru-RU.po
Labels: i18n

#889 New Crowdin updates
  src/data/catalogs.json
  src/locales/nb-NO.po
Labels: i18n

#890 New Crowdin updates
  src/locales/eu-ES.po
  src/locales/zh-CN.po
Labels: i18n

#895 New Crowdin updates
  src/data/catalogs.json
  src/locales/ar-SA.po
  src/locales/ca-ES.po
  src/locales/cs-CZ.po
  src/locales/de-DE.po
  src/locales/eo-UY.po
  src/locales/es-ES.po
  src/locales/eu-ES.po
  src/locales/fa-IR.po
  src/locales/fi-FI.po
  src/locales/fr-FR.po
  src/locales/gl-ES.po
  src/locales/he-IL.po
  src/locales/it-IT.po
  src/locales/ja-JP.po
  src/locales/kab.po
  src/locales/ko-KR.po
  src/locales/lt-LT.po
  src/locales/nb-NO.po
  src/locales/nl-NL.po
  src/locales/oc-FR.po
  src/locales/pl-PL.po
  src/locales/pt-BR.po
  src/locales/pt-PT.po
  src/locales/ru-RU.po
  src/locales/th-TH.po
  src/locales/uk-UA.po
  src/locales/zh-CN.po
  src/locales/zh-TW.po
Labels: i18n

#897 New Crowdin updates
  src/data/catalogs.json
  src/locales/zh-TW.po
Labels: i18n

#900 New Crowdin updates
  src/locales/ca-ES.po
  src/locales/eu-ES.po
  src/locales/lt-LT.po
Labels: i18n

#901 Add my instance and sort list
  README.md
Labels: documentation

#902 New Crowdin updates
  src/data/catalogs.json
  src/locales/lt-LT.po
  src/locales/pl-PL.po
Labels: i18n

#904 New Crowdin updates
  src/data/catalogs.json
  src/locales/uk-UA.po
Labels: i18n

#905 New Crowdin updates
  src/data/catalogs.json
  src/locales/uk-UA.po
Labels: i18n
